# Generated by Django 4.2.4 on 2023-08-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alkhidmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isProject', models.CharField(max_length=10)),
                ('isFutureProject', models.CharField(max_length=10)),
                ('projectDetailsCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraNCPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Muser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
                ('president', models.CharField(max_length=100)),
                ('vicePresident', models.CharField(default='', max_length=100, null=True)),
                ('secretory', models.CharField(default='', max_length=100, null=True)),
                ('viceSecretory', models.CharField(default='', max_length=100, null=True)),
                ('finance', models.CharField(default='', max_length=100, null=True)),
                ('publicity', models.CharField(default='', max_length=100, null=True)),
                ('womenContacts', models.CharField(default='', max_length=100, null=True)),
                ('studyCircle', models.CharField(default='', max_length=100, null=True)),
                ('youth', models.CharField(default='', max_length=100, null=True)),
                ('politicalCouncil', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('dawaProgramCount', models.IntegerField()),
                ('extraProgramCount', models.IntegerField()),
                ('NC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.nc')),
            ],
        ),
        migrations.CreateModel(
            name='UpperProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('attendence', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('held', models.IntegerField()),
                ('attendence', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPublicSecretariat', models.CharField(max_length=10)),
                ('activity', models.TextField()),
                ('tryOnCitizenIssue', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='NCYearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=20)),
                ('start', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('monthlyAdded', models.IntegerField()),
                ('addedFromStart', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='NCGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('NC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nc')),
            ],
        ),
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arkanInitial', models.IntegerField()),
                ('arkanAdded', models.IntegerField()),
                ('arkanMinus', models.IntegerField()),
                ('arkanNow', models.IntegerField()),
                ('active', models.IntegerField()),
                ('retired', models.IntegerField()),
                ('passive', models.IntegerField()),
                ('umeerwarInitial', models.IntegerField()),
                ('umeerwarAdded', models.IntegerField()),
                ('umeerwarMinus', models.IntegerField()),
                ('umeerwarNow', models.IntegerField()),
                ('arkanRwabit', models.IntegerField()),
                ('arkanRwabitNumber', models.IntegerField()),
                ('umeedwarRwabit', models.IntegerField()),
                ('umeedwarRwabitNumber', models.IntegerField()),
                ('karkun', models.IntegerField()),
                ('voters', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryNDawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='Karkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('NC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nc')),
            ],
        ),
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='No', max_length=100)),
                ('whatsapp', models.CharField(default='No', max_length=15)),
                ('email', models.CharField(default='No', max_length=100)),
                ('youtube', models.CharField(default='No', max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('previousBalance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('expenses', models.IntegerField()),
                ('upper', models.IntegerField()),
                ('currentBalance', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('president', models.CharField(max_length=100)),
                ('secretory', models.CharField(max_length=100)),
                ('NC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nc')),
            ],
        ),
        migrations.CreateModel(
            name='Arkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cetagory', models.CharField(max_length=10)),
                ('rbt1', models.CharField(default='', max_length=100)),
                ('rbt2', models.CharField(default='', max_length=100)),
                ('rbt3', models.CharField(default='', max_length=100)),
                ('rbt4', models.CharField(default='', max_length=100)),
                ('rbt5', models.CharField(default='', max_length=100)),
                ('rbt6', models.CharField(default='', max_length=100)),
                ('NC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nc')),
            ],
        ),
        migrations.CreateModel(
            name='AlkhidmatProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('alkhidmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alkhidmat')),
            ],
        ),
        migrations.AddField(
            model_name='alkhidmat',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.report'),
        ),
    ]
